#include "../s21_func/s21_string.h"

Suite *suite_memchr(void);
Suite *suite_memcmp(void);
Suite *suite_memcpy(void);
Suite *suite_strerror(void);
Suite *suite_strlen(void);
Suite *suite_strncat(void);
Suite *suite_memset(void);
Suite *suite_strchr(void);
Suite *suite_strpbrk(void);
Suite *suite_sscanf_c(void);
Suite *suite_sscanf_d(void);
Suite *suite_sscanf_f(void);
Suite *suite_sscanf_i(void);
Suite *suite_sscanf_n(void);
Suite *suite_sscanf_o(void);
Suite *suite_sscanf_p(void);
Suite *suite_sscanf_perc(void);
Suite *suite_sscanf_s(void);
Suite *suite_sscanf_u(void);
Suite *suite_sscanf_x(void);